/**
 * Cubedrill domain model.
 *
 * Two layers (see DOMAIN.md for the full glossary):
 *   - Catalog: built-in, shippable content (method → phase → set/group → case →
 *     algorithm, plus tags). Mostly static and extensible.
 *   - Personal: the user's data on top (chosen algorithms, learning status,
 *     authored algorithms). Local-first.
 *
 * The catalog is normalized: a `Case` owns its `Algorithm`s (1-to-many), while
 * the Case ↔ Set relationship is many-to-many via `SetMembership` (a case can
 * live in several sets — e.g. OLL 27 is in both Full OLL and 2-Look OLL — with a
 * set-relative name and group).
 */

// ---------------------------------------------------------------------------
// Shared
// ---------------------------------------------------------------------------

/** How a case is rendered/recognized. */
export type Visualization = '2D' | '3D';

/**
 * Semantic stickering mask. The rendering layer maps these to cubing.js
 * stickering; the domain only names the intent.
 */
export type StickeringMask = 'full' | 'cross' | 'f2l' | 'f2l-slot' | 'oll' | 'pll';

/** The four F2L target slots. F2L algorithms are authored per slot. */
export type F2LSlot = 'FR' | 'FL' | 'BR' | 'BL';

// ---------------------------------------------------------------------------
// Method & Phase
// ---------------------------------------------------------------------------

export type MethodId = string; // e.g. 'cfop'
export type PhaseId = string; // e.g. 'cross' | 'f2l' | 'oll' | 'pll'

export interface Method {
  id: MethodId;
  name: string; // 'CFOP'
  fullName?: string; // 'Fridrich Method'
  description?: string;
  /** Phases in solve order. */
  phaseIds: PhaseId[];
}

/**
 * `algorithmic` phases enumerate cases with algorithms (F2L/OLL/PLL).
 * `conceptual` phases hold techniques/tips rather than enumerated cases
 * (Cross, intuitive F2L) — modeled later via `Technique`.
 */
export type PhaseNature = 'algorithmic' | 'conceptual';

export interface Phase {
  id: PhaseId;
  methodId: MethodId;
  name: string; // 'OLL'
  fullName?: string; // 'Orientation of the Last Layer'
  description?: string;
  nature: PhaseNature;
  /** Solve order within the method. */
  order: number;
  /** Default stickering for this phase's cases (a set may override). */
  mask: StickeringMask;
  /** Preferred visualization, with the full list of what's supported. */
  defaultVisualization: Visualization;
  supportedVisualizations: Visualization[];
}

// ---------------------------------------------------------------------------
// Algorithm Set & Group
// ---------------------------------------------------------------------------

export type SetId = string; // 'oll-full' | 'oll-2look' | 'pll-full' | 'f2l-standard' ...

/** A loose tier label, useful for ordering the learning path. */
export type SetTier = 'beginner' | 'standard' | 'advanced' | 'expert' | 'full';

/** An ordered learning group within a set (e.g. Full OLL → "Dot"). */
export interface SetGroup {
  id: string; // unique within the set, e.g. 'dot'
  name: string; // 'Dot'
  order: number;
  description?: string;
}

export interface AlgorithmSet {
  id: SetId;
  phaseId: PhaseId;
  name: string; // 'Full OLL', '2-Look OLL'
  description?: string;
  tier?: SetTier;
  /** Learning-path order within the phase. */
  order: number;
  /** Optional overrides of the phase rendering defaults. */
  mask?: StickeringMask;
  defaultVisualization?: Visualization;
  supportedVisualizations?: Visualization[];
  /** Ordered groups; a membership references one of these by id. */
  groups: SetGroup[];
}

/**
 * Places a case into a set (many-to-many). Carries the set-relative display
 * label (e.g. "Sune" for OLL 27 inside 2-Look OLL) and the group/order the case
 * takes within that set.
 */
export interface SetMembership {
  setId: SetId;
  caseId: CaseId;
  /** id of a `SetGroup` within the set. */
  groupId?: string;
  /** Order within the group (or set, if ungrouped). */
  order: number;
  /** Set-relative name override; falls back to `Case.name`. */
  label?: string;
}

// ---------------------------------------------------------------------------
// Case & Algorithm
// ---------------------------------------------------------------------------

export type CaseId = string; // 'oll-27' | 'pll-t' | 'f2l-21'
export type AlgorithmId = string; // 'oll-27/0' | 'pll-t/1' ...

export interface Algorithm {
  id: AlgorithmId;
  /** Move sequence in standard notation. The setup/scramble is derived. */
  moves: string;
  /** F2L only: the slot this algorithm is authored for. */
  slot?: F2LSlot;
  /** True for algorithms generated by mirroring/rotating an authored one. */
  derived?: boolean;
  /** Marks the recommended algorithm for the case (or case+slot). */
  primary?: boolean;
  /** Where the algorithm came from (e.g. 'jperm'); user-authored if absent. */
  source?: string;
  tags?: TagId[];
  /** Optional fingertrick video (e.g. a YouTube URL). */
  videoUrl?: string;
  note?: string;
}

export interface Case {
  id: CaseId;
  phaseId: PhaseId;
  /** Canonical display name, e.g. 'OLL 27', 'T', 'F2L 21'. */
  name: string;
  /** Common nickname, e.g. 'Sune', 'T-Perm'. */
  nickname?: string;
  /** Numeric id where it exists (OLL/PLL/F2L numbering). */
  number?: number;
  /** Case-level tags (shape, recognition group, ...). */
  tags?: TagId[];
  /** Relative occurrence frequency (sums vary by phase; used for weighting). */
  prob?: number;
  /** Algorithms that solve this case (first/`primary` is the recommended one). */
  algorithms: Algorithm[];
}

// ---------------------------------------------------------------------------
// Tags
// ---------------------------------------------------------------------------

export type TagId = string;

export interface Tag {
  id: TagId;
  name: string;
  /** Where the tag applies. */
  scope: 'case' | 'algorithm' | 'both';
  /** Optional grouping for the filter UI (e.g. 'ergonomics', 'recognition'). */
  category?: string;
  /** True if it could be auto-derived from the cube state (future). */
  derived?: boolean;
}

// ---------------------------------------------------------------------------
// Catalog (the assembled built-in content)
// ---------------------------------------------------------------------------

export interface Catalog {
  methods: Method[];
  phases: Phase[];
  sets: AlgorithmSet[];
  cases: Case[];
  memberships: SetMembership[];
  tags: Tag[];
}

// ---------------------------------------------------------------------------
// Personal layer (user data — local-first)
// ---------------------------------------------------------------------------

export type LearningStatus = 'not-learned' | 'learning' | 'mastered';

/**
 * The user's state for a single case. Status is tracked per case for now
 * (per-slot is a possible future refinement for F2L).
 */
export interface PersonalEntry {
  caseId: CaseId;
  status: LearningStatus;
  /** The algorithm the user has chosen to learn for this case. */
  chosenAlgorithmId?: AlgorithmId;
  /** ISO timestamp of the last change. */
  updatedAt: string;
}

export interface PersonalSet {
  /** Keyed by caseId. Absence implies status 'not-learned'. */
  entries: Record<CaseId, PersonalEntry>;
  /** User-authored algorithms, keyed by the case they belong to. */
  authored: Record<CaseId, Algorithm[]>;
}
